import {createSnippetFile, readSnippetFile, snippetExists, writeSnippetFile} from "./snippets";
import {App} from "obsidian";
import * as css from "css";

// Obsidian's snippet management API is not part of the public typings.
interface CustomCssApp extends App {
	customCss: {
		setCssEnabledStatus(snippet: string, enabled: boolean): void;
		readSnippets(): Promise<void>;
		requestLoadSnippets(): Promise<void>;
	};
}

export const snippetName = "inlineAdmonitionsPluginReadOnly"
const snippetFilename = snippetName + ".css"
const header = `/*
WARNING: THIS FILE IS AUTOGENERATED BY THE INLINE ADMONITION PLUGIN. DO NOT MODIFY!
*/
`;

export async function setCssForClass(app: App, className: string, css: string) {
	const updatedCss = _setCssForClass(className, css, await cssFileContents(app));
	//https://discord.com/channels/686053708261228577/840286264964022302/1220596234545401906
	const customCss = (app as CustomCssApp).customCss;
	customCss.setCssEnabledStatus(snippetName, true);
	await customCss.readSnippets();
	await customCss.requestLoadSnippets();
	return writeSnippetFile(app, snippetFilename, updatedCss);
}

export async function wipeCss(app: App) {
	if (await snippetExists(app, snippetFilename)) {
		return writeSnippetFile(app, snippetFilename, header);
	} else {
		return createSnippetFile(app, snippetFilename, header);
	}
}

// ==========
//  INTERNAL
// ==========

async function cssFileContents(app: App): Promise<string> {
	return readSnippetFile(app, snippetFilename);
}

// Sets the css declarations for the className to cssClassContent within the cssFileContent
export function _setCssForClass(className: string, cssClassDeclarations: string, cssFileContent: string): string {
	// TODO - add source
	const fileObj = css.parse(cssFileContent, {});
	const rules = fileObj.stylesheet?.rules ?? [];

	for (const rule of rules) {
		const r = rule as css.Rule;
		if (r.selectors?.contains("." + className)) {
			r.declarations = _makeCssRule(className, cssClassDeclarations).declarations;
			return css.stringify(fileObj);
		}
	}
	rules.push(_makeCssRule(className, cssClassDeclarations));
	return css.stringify(fileObj);
}

function _makeCssRuleString(className: string, cssDeclarations: string): string {
	// TODO - The ".iad" is here to increase the precedence.  I dont like it
	return ".iad." + className + " {\n" + cssDeclarations + "\n}";
}

function _makeCssRule(className: string, cssDeclarations: string): css.Rule {
	const cssString = _makeCssRuleString(className, cssDeclarations);
	return (css.parse(cssString, {}).stylesheet?.rules ?? [])[0];
}
